INSERT INTO USER 		(USER_ID, USER_NAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USER_TYPE) VALUES (1, 'M_JORDAN', 'mj@nba.com', 'Michael', 'Jordan', 'mj1234', 'ADMIN');
INSERT INTO USER 		(USER_ID, USER_NAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USER_TYPE) VALUES (2, 'K_BRYANT', 'kb@nba.com','Kobe', 'Bryant', 'kb1234', 'NADMIN');
INSERT INTO USER 		(USER_ID, USER_NAME, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, USER_TYPE) VALUES (3, 'L_JAMES', 'lb@nba.com','Lebron', 'James', 'lb1234', 'NADMIN');

INSERT INTO RESTAURANT 	(ID, ADDRESS, DESCRIPTION, NAME, WEBSITEURL) VALUES (1, 'RESTARANT1 ADDRESS', 'RESTARANT1 DESC','RESTARANT1 NAME', 'RESTARANT1 WEB URL');
INSERT INTO RESTAURANT 	(ID, ADDRESS, DESCRIPTION, NAME, WEBSITEURL) VALUES (2, 'RESTARANT2 ADDRESS', 'RESTARANT2 DESC','RESTARANT2 NAME', 'RESTARANT2 WEB URL');
